// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvrakzqovzgsdcerysmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2cmFrenFvdnpnc2RjZXJ5c210Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NzQ3NzUsImV4cCI6MjA1NDM1MDc3NX0.25ROCPjgIBjTBTq5mVkP8Nv844KJ1mFYtYFIE-rTtKM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);